### ISSUE TITLE
Too Soon?

### ISSUE THREAD

**Issue by martinthomson** [martinthomson/http-replay#1]
@mnot, WDYT?

**Comment by wtarreau** [comment]
And why not simply "Unsafe", it would even cover future use cases of
a retry unrelated to timing (eg: avoid reusing certain shared idle
connections, or stuff like this).

**Comment by martinthomson** [comment]
I think that we need to be careful about trying to address use cases that we don't understand.  I was being obtuse, but the idea would be s/Too Early/Too Soon/

**Comment by wtarreau** [comment]
That was my understanding as well, and I was suggesting s/Too Early/Unsafe/.
But OK maybe it would be too broad a scope.

**Comment by wtarreau** [comment]
I've thought more about it and would like to propose "Not Processed". It's more accurate, implies retries safety and could be extended to future uses if needed. We'd simply start by saying that 0-RTT clients must be ready to receive this and deal with it, and that early-data requests resulting in "not processed" must be retried without early data.

**Comment by mnot** [comment]
`Not Processed` is pretty generic; I think in this case, we want to let the client know exactly what was wrong, so they can take the appropriate action. Specifically, the client needs to know that this request won't succeed if it occurs in 0RTT data.

**Comment by wtarreau** [comment]
I tend to think that a failed request must never be retried in 0RTT anyway as if it was not processed, most likely it's sensitive. Future uses might define an extra header field indicating what constraints were not satisfied.

**Comment by wtarreau** [comment]
Otherwise we go the very specific route and return "Early Data not acceptable" and this status code will be dedicated to this specific use case.

**Comment by martinthomson** [comment]
My preference is to make this specific to this use case.  We have a range of "not processed" signals already that might be used to signal that the server discarded a request.  The advantage of this signal is that it allows a client to make the request after the handshake completes.

**Comment by wtarreau** [comment]
OK, convinced :-)

**Comment by mnot** [comment]
Back to the original issue -- "too soon" is cute but "too early" is directly connected to the terminology.

**Comment by martinthomson** [comment]
Yeah, cute is fine only if it isn't beaten out by actual value.
