### ISSUE TITLE
Talk about requests that span 0-RTT and 1-RTT

### ISSUE THREAD

**Issue by martinthomson** [martinthomson/http-replay#16]
As a single stream, requests can start in early data and finish after the handshake completes.  This isn't necessarily a problem, but we should explain what the thinking is.

The model we've adopted here is that once the handshake is complete, whether the first part of the request was in early data doesn't matter.  This is on the basis that early data is retroactively blessed once the handshake completes.  What matters most is when the actions are triggered.  If a request is processed before the handshake completes, even partially, then the question of replay becomes relevant.

Needs some text.

**Comment by wtarreau** [comment]
This is where I was trying to use "transported" or "conveyed" as early data,
to imply that at least some of the request was possibly unsafe (though my
wording possibly was not clear).

**Comment by mnot** [comment]
I think the language martin uses above is a good starting point.

**Comment by kaduk** [comment]
For what it's worth, my review comment that prompted this was carefully worded to avoid mentioning "one stream" or "two streams".  In some sense, it doesn't really matter which mental model someone uses to think about it, they can still reach the correct conclusion.  I believe it will be possible to similarly carefully word text for this document that does not rely on a "single stream" or "two streams" model.

**Comment by martinthomson** [comment]
The question of the model of how the TLS API presents early data is different from how HTTP manages this.  I think that the important point for HTTP is that early data is concatenated with not-early data.  I see that we basically lost this in @mnot's latest round of edits.  I'll open an issue.
