### ISSUE TITLE
Allow the intermediary to generate 4NN (Too Early)

### ISSUE THREAD

**Issue by martinthomson** [martinthomson/http-replay#23]
@ghedo asks that we explicitly allow this.  This is reasonable.

**Comment by wtarreau** [comment]
I would have sworn it was already mentionned but I could find no trace of it (we probably lost it during the early refactoring we did to early-data). Yes, the intermediary is supposed to know that some requests or methods will not be accepted and will have to emit 4NN itself in this case. Similarly it may have to request 1-RTT for authentication or to process a sensitive POST.

**Comment by martinthomson** [comment]
OK, I just double-checked the text and found that this is permitted.

1. we use the word "server" as opposed to "origin server" when describing this.

2. we explicitly allow an intermediary to use the status code:

> A gateway that isn't certain about server support SHOULD either delay
forwarding the request until the TLS handshake completes, or send a 4NN (Too
Early) status code in response.  A gateway that is uncertain about whether an
origin server supports the `Early-Data` header field SHOULD disable early data.

The problem is that the remainder of that paragraph is a little contradictory.  I'll fix that.

**Comment by martinthomson** [comment]
I take that back, it's OK.
