### ISSUE TITLE
Let the intermediary retry

### ISSUE THREAD

**Issue by martinthomson** [martinthomson/http-replay#29]
Several people have pointed out this as a possible performance enhancement.  I can't find a hole, assuming that the 4NN is reliably implemented by servers.

**Comment by wtarreau** [comment]
I'm fine with it as well. I'll try to provide a diagram that we can integrate showing multiple levels of 0-RTT to help everyone understand the reasons for certain choices.

**Comment by martinthomson** [comment]
I was thinking that a minimal solution here would be to remove the prohibition and leave it at that.  An intermediary is also a server, so as long as we don't overuse "origin server", we should be OK.

**Comment by wtarreau** [comment]
Possibly, but I've noticed several times that server-side developers rarely consider intermediaries as servers (they are their clients after all) while intermediary developers find this natural. Here it should not cause any issue I guess.

**Comment by mnot** [comment]
Do you mean *all* intermediaries -- including forward proxies -- here?

**Comment by martinthomson** [comment]
Victor convinced me that this is OK.  Note that a forward proxy is a bad idea for other reasons, which should be sufficient to stop their use in this case.
