### ISSUE TITLE
risks for the client

### ISSUE THREAD

**Issue by wtarreau** [martinthomson/http-replay#5]
"This gives a client explicit control over whether a given request is exposed to the risk of replay."

For me the first risk the client takes by sending a request as early data is to see it being rejected and having to retry it differently. It's important because it helps decide whether or not idempotent requests should be sent this way or not, regardless of the replay risk.

In fact I *think* that if we place the replay avoidance paragraph before "reducing the risk", we may more easily enumerate the double risk the client has to accept to take (request being replayed, request getting rejected by the server).

**Comment by martinthomson** [comment]
@wtarreau, take a look at Mark's adjusted text.  I think that it might make this clearer.

**Comment by wtarreau** [comment]
The latest version (which I'm assuming contains Mark's adjusted text) is way better in my opinion.
