### ISSUE TITLE
risk of getting multiple early-data header fields

### ISSUE THREAD

**Issue by wtarreau** [martinthomson/http-replay#6]
"An intermediary MUST NOT add this header field with a value of “0” or remove a header field if it has a value of “1”" : I see the point in case a request is transported over several gateways, but then it conflates the client's initial intent and what the next hope received. For example, it might be complicated for a client to remove this header field at the last moment once the connection is being established and the server says it doesn't accept early data. So the client might leave some early-data header fields in its request buffer and send them over a perfectly safe connection. But at the same time we don't want to let second or third level gateways remove the header field. I think in fact we need 3 values for the header field, the one used by the client and the one passed to the server. We want more or less "Early-data: sent" set by the client, replaced with "Early-data: received" by the first gateway, or the header field being removed (or set to "none") if in the end the request was not received as early data. And only "sent" would be allowed to be replaced, with "received" being sticky. I can propose some text.

**Comment by wtarreau** [comment]
And if the intermediary retries by itself after waiting for the TLS handshake, it will need to remove the header field. Thus if we don't need the server to know that a request was sent as early data but that the handshake was properly validated, the intermediary definitely needs to remove the header field once the handshake is validated.

**Comment by martinthomson** [comment]
I think that moving to a tri-state is more complicated than we need.  The point here is that the header field appear if there is a *chance* that it might be replayed.  There are definitely cases where the gateway receives the request and the handshake is done.  That might be for any number of reasons: because the client couldn't fit the request into early data, so the end of the request spilled over into the 1-RTT data; because the gateway takes long enough to start forwarding the request that the handshake completes; or maybe because the client forgets or is unable to remove the marking.

I see how a "received" vs "sent" fixes this, but is it worth the additional complexity?

**Comment by martinthomson** [comment]
OK, I understand better now.  If a gateway receives the header field, then how does it distinguish between the case where the last hop used 0-RTT and the case where a previous hop used 0-RTT?

**Comment by wtarreau** [comment]
> I see how a "received" vs "sent" fixes this, but is it worth the additional
> complexity?

I really think so, I'll try to provide a diagram to show it. It will cover
two use cases :
  - the one where the client uses early data to connect to a prudent TLS
    terminator which always waits for the end of the handshake ; it would
    be counter-productive to let the server return the 4NN asking for a
    retry there ;

  - when a CDN is involved and uses 0RTT on both sides, it's important to
    ensure there's a way for the server side to avoid confusion between
    what the client did and what the CDN did (ie: if there was a single
    risk, it must stay).

I started to write down on paper an example but I'd like to write a few
of them to ensure there's no corner case left.

In the end it should even remove some of the complexity by avoiding an
enumeration of rules.

**Comment by wtarreau** [comment]
In fact we can avoid the 3-state header field if we get back to what we originally proposed during our face-to-face discussion : mandate that sending HTTP traffic in early data implies the ability to retry upon 4NN response. In this case, a client doesn't have to send any header field (which simplifies the retry), a "dumb" TLS terminator doesn't have to touch header fields and simply needs to wait for the handshake, and an optimized TLS terminator will add this header field when the request was received as early data prior to the handshake. This is even more in line with existing deployments since clients don't send any header field right now and TLS endpoints currently wait for the end of the handshake, so this would allow a smoother move to the safe behaviour.

**Comment by martinthomson** [comment]
I like that.  I think that we might already have the MUST support the 4NN thing, but I'll review Mark's PR and double-check.
