### ISSUE TITLE
servers must not generate 422 without early data header field

### ISSUE THREAD

**Issue by wtarreau** [martinthomson/http-replay#7]
"A server SHOULD NOT generate the 422 (Too Early) status code unless the request includes an Early-Data header field with a value of “1”"

I think we should be stricter here and say MUST NOT. I still can't find a case where a server could decide to emit this code without being absolutely certain the client would be able to retry. The biggest problem I'm seeing is that SHOULD NOT will be enough of a signal for some dirty server implementations to use it to force a generic retry (eg: flow control) and that will force clients to implement support for it, diverting the initial purpose. So better use MUST NOT.

**Comment by martinthomson** [comment]
My thought was that if the server wanted to use the status code (which will be interpreted as a generic 4xx) rather than process the request, then that's OK.  The same goes for an intermediary that is unable to retry the request.

**Comment by wtarreau** [comment]
Got it. Then we should probably say "The server MUST NOT assume a client's ability to retry if the request doesn't contain an Early-Data header field, and as such SHOULD NOT emit the 4NN status code". I really think we need to put a MUST somewhere to avoid the status code being abused for generic use outside of the early-data scope.

**Comment by mnot** [comment]
LGTM.
